### PR TITLE
namespace variables

### LINKED ISSUE #1: Prefixing variables
> note: this is a repost of @leepowellcouk issue comment - https://github.com/mojotech/jeet/issues/123#issuecomment-32470743 . apologies for not having issues enabled. 

Just an idea - for Grate, is it worth prefixing the settings variables? Just to avoid any potential conflicts with other plugins?

```
grate-gutter = 3
grate-parent-first = false
grate-layout-direction = LTR
```

I've noticed when mashing a few stylus libraries together that occasionally you encounter conflicts around global variables.

edit: variables using underscores

### PR DESCRIPTION
**Pull request by kylemac**
- closes #1

### CODE REVIEW

**Comment by leepowelldev** [comment]
I'm guessing if this is going to be commonly used alongside axis, maybe follow their variable naming convention of using `-` instead of `_` ?

**Comment by jescalan** [comment]
Yeah agreed @leepowellcouk - for css variables I tend to use dashes rather than underscores for some of [these reasons](http://stackoverflow.com/questions/7560813/why-are-dashes-preferred-for-css-selectors-html-attributes)

**Comment by kylemac** [comment]
I'll squash before we merge

**Comment by jescalan** [comment]
:+1:

**Pull request merged**
